#!/bin/bash 

#SBATCH -p holyseasgpu  #Partition to submit to 
#SBATCH -n 1  #Number of cores 
#SBATCH --gres=gpu
#SBATCH -t 5  #Runtime in minutes 
#SBATCH --mem-per-cpu=100 #Memory per cpu in MB (see also --mem) 
#SBATCH --constraint=cuda-7.5

# srun --mem-per-cpu=2000 -p holyseasgpu -n 1 --gres=gpu:1 --constraint=cuda-7.5 --pty -t 0-01:00 /bin/bash

#module load pycuda/2015.1.3-fasrc01

python hw22.py 
