#!/bin/bash 

#SBATCH -p holyseasgpu  #Partition to submit to 
#SBATCH -n 1  #Number of cores 
#SBATCH --gres=gpu
#SBATCH -t 5  #Runtime in minutes 
#SBATCH --mem-per-cpu=100 #Memory per cpu in MB (see also --mem) 
#SBATCH --constraint=cuda-7.5

module load pycuda/2015.1.3-fasrc01

python hw22.py 

